name: Development CI

on:
  push:
    branches:
      - development

jobs:
  linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: update ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libclang-9-dev libclang-common-9-dev
        ls /usr/bin/gcc*
        ls /usr/bin/clang*
    - name: configure on ${{ matrix.os }}
      env:
        CC: clang-9
        CXX: clang++-9
        CI: true
      run: |
        cmake -S . -B build
    - name: build on ${{ matrix.os }}
      run: cmake --build build
