name: Development CI

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: prepare linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
    - name: build
      run: |
        mkdir build
        cd build
        cmake ../
        make
      env:
        CI: true
