name: Development CI

on:
  push:
    branches:
      - development

jobs:
  linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: update ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-cache search libcxx
        sudo apt-cache search clang
        ls /usr/bin/gcc*
    - name: configure on ${{ matrix.os }}
      env:
        CC: gcc-9
        CXX: g++-9
        CI: true
      run: |
        cmake -S . -B build
    - name: build on ${{ matrix.os }}
      run: cmake --build build
