name: Development CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        mkdir build
        cd build
        cmake ../
        make
      env:
        CI: true
